import { IPost } from "../interfaces";

export const mockPostsByAuthors: IPost[] = [
  {
    id: 1010,
    content: "Exploring advanced React Native animations!",
    author: {
      id: 101,
      userName: "Alice Johnson",
      firstName: "Alice",
      lastName: "Johnson",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
    comments: [
      {
        id: 1001,
        content: "Which book was it?",
        author: {
          id: 102,
          userName: "Bob Smith",
          firstName: "Alice",
          lastName: "Johnson",
          avatar: "https://i.pravatar.cc/150?img=2",
        },
      },
      {
        id: 1002,
        content: "I love React Native too!",
        author: {
          id: 103,
          userName: "Charlie Daniels",
          firstName: "Charlie",
          lastName: "Daniels",
          avatar: "https://i.pravatar.cc/150?img=3",
        },
      },
    ],
  },
  {
    id: 1011,
    content: "Just deployed my first app to the Play Store!",
    author: {
      id: 101,
      userName: "Alice Johnson",
      firstName: "Alice",
      lastName: "Johnson",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
    comments: [],
  },
  {
    id: 1012,
    content: "Starting a new blog on mobile dev tips.",
    author: {
      id: 101,
      userName: "Alice Johnson",
      firstName: "Alice",
      lastName: "Johnson",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
    comments: [],
  },
  {
    id: 1013,
    content: "React Navigation 6 is 🔥",
    author: {
      id: 101,
      userName: "Alice Johnson",
      firstName: "Alice",
      lastName: "Johnson",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
    comments: [],
  },

  {
    id: 1020,
    content: "Trying out Expo Router this week!",
    author: {
      id: 102,
      userName: "Bob Smith",
      firstName: "Bob",
      lastName: "Smith",
      avatar: "https://i.pravatar.cc/150?img=2",
    },
    comments: [],
  },
  {
    id: 1021,
    content: "Dark mode or light mode – what do you prefer?",
    author: {
      id: 102,
      userName: "Bob Smith",
      firstName: "Bob",
      lastName: "Smith",
      avatar: "https://i.pravatar.cc/150?img=2",
    },
    comments: [],
  },
  {
    id: 1022,
    content: "Typescript generics are confusing but powerful.",
    author: {
      id: 102,
      userName: "Bob Smith",
      firstName: "Bob",
      lastName: "Smith",
      avatar: "https://i.pravatar.cc/150?img=2",
    },
    comments: [],
  },
  {
    id: 1023,
    content: "React Native Paper vs UI Kitten – any opinions?",
    author: {
      id: 102,
      userName: "Bob Smith",
      firstName: "Bob",
      lastName: "Smith",
      avatar: "https://i.pravatar.cc/150?img=2",
    },
    comments: [],
  },
  {
    id: 1030,
    content: "Started building a personal finance tracker app.",
    author: {
      id: 103,
      userName: "Charlie Daniels",
      firstName: "Charlie",
      lastName: "Daniels",
      avatar: "https://i.pravatar.cc/150?img=3",
    },
    comments: [],
  },
  {
    id: 1031,
    content: "Just discovered Zustand – simple and powerful.",
    author: {
      id: 103,
      userName: "Charlie Daniels",
      firstName: "Charlie",
      lastName: "Daniels",
      avatar: "https://i.pravatar.cc/150?img=3",
    },
    comments: [],
  },
  {
    id: 1032,
    content: "Refactoring legacy JS code to TypeScript.",
    author: {
      id: 103,
      userName: "Charlie Daniels",
      firstName: "Charlie",
      lastName: "Daniels",
      avatar: "https://i.pravatar.cc/150?img=3",
    },
    comments: [],
  },
  {
    id: 1033,
    content: "Is anyone using Jotai for state management?",
    author: {
      id: 103,
      userName: "Charlie Daniels",
      firstName: "Charlie",
      lastName: "Daniels",
      avatar: "https://i.pravatar.cc/150?img=3",
    },
    comments: [],
  },
  {
    id: 1040,
    content: "Learning TypeScript with React Native is fun!",
    author: {
      id: 104,
      userName: "Diana Prince",
      firstName: "Diana",
      lastName: "Prince",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
    comments: [],
  },
  {
    id: 1041,
    content: "Custom hooks save me so much time!",
    author: {
      id: 104,
      userName: "Diana Prince",
      firstName: "Diana",
      lastName: "Prince",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
    comments: [],
  },
  {
    id: 1042,
    content: "Anyone using Reanimated 3 yet?",
    author: {
      id: 104,
      userName: "Diana Prince",
      firstName: "Diana",
      lastName: "Prince",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
    comments: [],
  },
  {
    id: 1043,
    content: "Going to try Dripsy for design tokens!",
    author: {
      id: 104,
      userName: "Diana Prince",
      firstName: "Diana",
      lastName: "Prince",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
    comments: [],
  },
  {
    id: 1050,
    content: "Just discovered Tamagui, looks promising!",
    author: {
      id: 105,
      userName: "Ethan Hunt",
      firstName: "Ethan",
      lastName: "Hunt",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    comments: [],
  },
  {
    id: 1051,
    content: "Building a modular monorepo setup with Turbo.",
    author: {
      id: 105,
      userName: "Ethan Hunt",
      firstName: "Ethan",
      lastName: "Hunt",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    comments: [],
  },
  {
    id: 1052,
    content: "Using Husky + lint-staged in my RN projects now.",
    author: {
      id: 105,
      userName: "Ethan Hunt",
      firstName: "Ethan",
      lastName: "Hunt",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    comments: [],
  },
  {
    id: 1053,
    content: "Which CI/CD tools are best for RN apps?",
    author: {
      id: 105,
      userName: "Ethan Hunt",
      firstName: "Ethan",
      lastName: "Hunt",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    comments: [],
  },
];
